### ISSUE TITLE
Overflow BV operators

### ISSUE THREAD

**Issue by barrettcw** [SMT-LIB/SMT-LIB-2#2]
Add overflow operators to QF_BV logic.

From Pascal's email 12/22/2022:

There has been renewed requests to introduce within SMT-LIB some overflow predicates for bit vectors, i.e., predicates indicating if the result of an operation on bit vectors is not corresponding to the expected integer, because of the fixed bit width.  Impacted operations are: neg, add, sub, mul, div.

According to the initial request, we plan to introduce the following predicates:

bvnego

bvuaddo bvsaddo

bvusubo bvssubo

bvumulo bvsmulo

bvsdivo

with the same arguments as the corresponding operations, returning true if there is an overflow, and false if not.  We do not plan to distinguish whether the result is over or below the expected value.  We plan this evolution both for the 2.6 and the 3.0 versions of SMT-LIB.

**Comment by fontainep** [comment]
A comment from Maria Paola:

I'd rather suggest, e.g.,

bv-neg-o or bv-neg-of or at least bvnegof

that is, abbreviating overflow as 'of' and not only as 'o' and adding hyphens to separate the word fragments. I think it'd increase the readability and would be an aesthetic improvement.

Question: are the names already used by cvc/z3/bitwuzla?

Maria Paola has a point: bvnego is cryptic.  bvneg is history, but bvneg-overflow would perfectly make sense.

**Comment by fontainep** [comment]
Missing functions for SMT-LIB 2 are actually in the QF_BV logic.

**Comment by mpreiner** [comment]
> Question: are the names already used by cvc/z3/bitwuzla?
> 

Yes, these names are already used by cvc5, z3 and Bitwuzla (and Boolector).

> Maria Paola has a point: bvnego is cryptic. bvneg is history, but bvneg-overflow would perfectly make sense.

For consistency reasons, I'd avoid introducing theory symbols with hyphens. The BV theory does not define any theory symbols with hyphens. Adding `-overflow` seems to be too verbose in my opinion. Adding `of` instead of `o` may be confused with `of` instead of `overflow`, i.e., `bvnegof` would read as bit-vector negation of a term instead of indicating whether an overflow happened when negating a bit-vector term.

**Comment by mpreiner** [comment]
> For SMT-LIB 2, there is no bvsub, or bvsdiv, therefore there is no need for the corresponding overflow operators. Otherwise I suggest the following changes to the FixedSizeBitVectors.smt2 file:

I'm confused about this statement. We have `bvsub` and `bvsdiv` in SMT-LIB?

**Comment by aniemetz** [comment]
I agree with @mpreiner that we should avoid introduce symbols with hyphens. It is not only inconsistent with the BV theory, but also across SMT-LIB in general, as far as I know. I also think `bvnegoverflow` would be quite verbose, and `bvnegof` confusing. I can live with the former, but am against the latter.

**Comment by fontainep** [comment]
> > Question: are the names already used by cvc/z3/bitwuzla?
> 
> Yes, these names are already used by cvc5, z3 and Bitwuzla (and Boolector).

Then the question is settled.  We must not enforce new names, at least not in SMT-LIB 2.

Names will certainly be refactored for SMT-LIB 3 though.

**Comment by fontainep** [comment]
> > For SMT-LIB 2, there is no bvsub, or bvsdiv, therefore there is no need for the corresponding overflow operators. Otherwise I suggest the following changes to the FixedSizeBitVectors.smt2 file:
> 
> I'm confused about this statement. We have `bvsub` and `bvsdiv` in SMT-LIBv2.

This statement was wrong.  However the function are defined in the logic file though.

Thank you, Aina and Mathias, for your quick and wise input!

**Comment by mpreiner** [comment]
Actually, z3 has different names for the predicates: e.g., instead of `bvsmulo` it has `bvsmul_noovfl`, which is the same as `(not (bvsmulo ...))`

**Comment by fontainep** [comment]
I do not feel strongly about names, but indeed bvsmulovfl might be a sweet spot.  Aina, Mathias, from the top of your head, do you see people that we must ask now about the names? 
Unfortunately, whatever names we choose, some people will not be happy, because there is no perfect solution.  The more people agree now though, the quicker the discussion afterwards will be.

**Comment by fontainep** [comment]
Here is a diff of the proposed changes for FixedSizeBitVectors.smt2

*** FixedSizeBitVectors.smt2.orig	2023-10-26 11:57:05.985755914 +0200
--- FixedSizeBitVectors.smt2	2023-10-26 11:55:32.785335852 +0200
***************
*** 39,44 ****
--- 39,52 ----
   :funs_description "
      All function symbols with declaration of the form
  
+       ((_ bv0 m) (_ BitVec m))
+ 
+     where m is a numeral
+  "
+ 
+  :funs_description "
+     All function symbols with declaration of the form
+ 
        (concat (_ BitVec i) (_ BitVec j) (_ BitVec m))
  
      where
***************
*** 107,112 ****
--- 115,126 ----
  
         bv2nat(b) := b(m-1)*2^{m-1} + b(m-2)*2^{m-2} + ⋯ + b(0)*2^0
  
+    o bv2int, which takes a bitvector b: [0, m) → {0, 1}
+      with 0 < m, and returns an integer in the range [- 2^(m - 1), 2^(m - 1)),
+      and is defined as follows:
+ 
+        bv2int(b) := if b(m-1) = 0 then bv2nat(b) else bv2nat(b) - 2^m
+ 
     o nat2bv[m], with 0 < m, which takes a non-negative integer
       n and returns the (unique) bitvector b: [0, m) → {0, 1}
       such that
***************
*** 140,145 ****
--- 154,165 ----
     times the length of the sequence, then the term represents nat2bv[m](n).
     For example, #xFF is equivalent to #b11111111.
  
+    - Zero bitvector
+ 
+    Terms denoting the zero bitvector can be built with bv0, defined as follows
+ 
+    [[(_ bv0 m)]] := λx:[0, m). 0
+ 
     - Function symbols for concatenation
  
     [[(concat s t)]] := λx:[0, n+m). if (x < m) then [[t]](x) else [[s]](x - m)
***************
*** 181,186 ****
--- 201,220 ----
                         then [[s]]
                         else nat2bv[m](bv2nat([[s]]) rem bv2nat([[t]]))
  
+    We also define the following predicates
+ 
+    [[(bvnego s)]] := bv2int([[s]]) >= 2^(m - 1)
+ 
+    [[(bvuaddo s t)]] := (bv2nat([[s]]) + bv2nat([[t]])) >= 2^m
+ 
+    [[(bvsaddo s t)]] := (bv2int([[s]]) + bv2int([[t]])) >= 2^(m - 1) or
+                         (bv2int([[s]]) + bv2int([[t]])) < -2^(m - 1)
+ 
+    [[(bvumulo s t)]] := (bv2nat([[s]]) * bv2nat([[t]])) >= 2^m
+ 
+    [[(bvsmulo s t)]] := (bv2int([[s]]) * bv2int([[t]])) >= 2^(m - 1) or
+                         (bv2int([[s]]) * bv2int([[t]])) < -2^(m - 1)
+ 
     - Shift operations
  
     Suppose s and t are both terms of sort (_ BitVec m), m > 0.  We make use of

**Comment by fontainep** [comment]
Here is a diff of the proposed changes for QF_BV.smt2

*** QF_BV.smt2.orig	2023-10-26 11:57:18.929834906 +0200
--- QF_BV.smt2	2023-10-26 11:46:08.067228977 +0200
***************
*** 75,80 ****
--- 75,90 ----
          the value of the second argument)
      (bvult (_ BitVec m) (_ BitVec m) Bool)
        - binary predicate for unsigned less-than
+     (bvnego (_ BitVec m) Bool)
+       - overflow predicate for 2's complement unary minus
+     (bvuaddo (_ BitVec m) (_ BitVec m) Bool)
+       - overflow predicate for unsigned addition modulo 2^m
+     (bvsaddo (_ BitVec m) (_ BitVec m) Bool)
+       - overflow predicate for signed addition on m-bit 2's complement
+     (bvumulo (_ BitVec m) (_ BitVec m) Bool)
+       - overflow predicate for unsigned multiplication modulo 2^m
+     (bvsmulo (_ BitVec m) (_ BitVec m) Bool)
+       - overflow predicate for signed multiplication on m-bit 2's complement
  
    Defined below:
  
***************
*** 102,107 ****
--- 112,123 ----
        - Arithmetic shift right, like logical shift right except that the most
          significant bits of the result always copy the most significant
          bit of the first argument.
+     (bvusubo (_ BitVec m) (_ BitVec m) Bool)
+       - overflow predicate for unsigned subtraction modulo 2^m
+     (bvssubo (_ BitVec m) (_ BitVec m) Bool)
+       - overflow predicate for signed 2's complement m-bit subtraction
+     (bvsdivo (_ BitVec m) (_ BitVec m) Bool)
+       - overflow predicate for 2's complement signed division
  
      The following symbols are parameterized by the numeral i, where i >= 1.
  
***************
*** 222,227 ****
--- 238,246 ----
                 (bvule s t)))
      (bvsgt s t) abbreviates (bvslt t s)
      (bvsge s t) abbreviates (bvsle t s)
+     (bvusubo s t) stands for (bvult s t)
+     (bvssubo s t) abbreviates (or (bvsaddo s (bvneg t)) (and (bvnego t) (bvslt s (_ bv0 m))))
+     (bvsdivo s t) abbreviates (and (bvnego s) (= t (bvssub (_ bv0 m) 1)))
  
    - Other operations

**Comment by aniemetz** [comment]
I think at the moment, the only solvers implementing exactly these predicates are cvc5 and Bitwuzla (Boolector implements a variant, where the return value is a bit-vector of size 1). Z3 implements a predicate that represents the negation (and thus not exactly these predicates), so I guess there will not be too many name clashes.

**Comment by mpreiner** [comment]
> Here is a diff of the proposed changes for QF_BV.smt2
> 
> ```
> *** QF_BV.smt2.orig	2023-10-26 11:57:18.929834906 +0200
> --- QF_BV.smt2	2023-10-26 11:46:08.067228977 +0200
> ***************
> *** 75,80 ****
> --- 75,90 ----
>           the value of the second argument)
>       (bvult (_ BitVec m) (_ BitVec m) Bool)
>         - binary predicate for unsigned less-than
> +     (bvnego (_ BitVec m) Bool)
> +       - overflow predicate for 2's complement unary minus
> +     (bvuaddo (_ BitVec m) (_ BitVec m) Bool)
> +       - overflow predicate for unsigned addition modulo 2^m
> +     (bvsaddo (_ BitVec m) (_ BitVec m) Bool)
> +       - overflow predicate for signed addition on m-bit 2's complement
> +     (bvumulo (_ BitVec m) (_ BitVec m) Bool)
> +       - overflow predicate for unsigned multiplication modulo 2^m
> +     (bvsmulo (_ BitVec m) (_ BitVec m) Bool)
> +       - overflow predicate for signed multiplication on m-bit 2's complement
>   
>     Defined below:
>   
> ***************
> *** 102,107 ****
> --- 112,123 ----
>         - Arithmetic shift right, like logical shift right except that the most
>           significant bits of the result always copy the most significant
>           bit of the first argument.
> +     (bvusubo (_ BitVec m) (_ BitVec m) Bool)
> +       - overflow predicate for unsigned subtraction modulo 2^m
> +     (bvssubo (_ BitVec m) (_ BitVec m) Bool)
> +       - overflow predicate for signed 2's complement m-bit subtraction
> +     (bvsdivo (_ BitVec m) (_ BitVec m) Bool)
> +       - overflow predicate for 2's complement signed division
>   
>       The following symbols are parameterized by the numeral i, where i >= 1.
>   
> ***************
> *** 222,227 ****
> --- 238,246 ----
>                  (bvule s t)))
>       (bvsgt s t) abbreviates (bvslt t s)
>       (bvsge s t) abbreviates (bvsle t s)
> +     (bvusubo s t) stands for (bvult s t)
> +     (bvssubo s t) abbreviates (or (bvsaddo s (bvneg t)) (and (bvnego t) (bvslt s (_ bv0 m))))
> +     (bvsdivo s t) abbreviates (and (bvnego s) (= t (bvssub (_ bv0 m) 1)))
>   
>     - Other operations
> ```

Instead of `(bvssub (_ bv0 m) 1)` it would be better to use `(bvnot (_ bv0 m))`

**Comment by fontainep** [comment]
> Instead of (bvssub (_ bv0 m) 1) it would be better to use (bvnot (_ bv0 m))

Actually, I was first thinking that it was preferable to stay in arithmetic, but my version is not syntactically correct.  I'll opt for yours.  Thanks!

**Comment by fontainep** [comment]
Levent Erkok made the following comment by mail:

It's been almost a year you circulated the above email, but I just noticed a potential naming confusion: For negation and division, overflow only makes sense in the signed case. (Neither operation overflows for unsigned arguments.) But in the former case you called the predicate `bvnego`, while in the latter it's called `bvsdivo`. For consistency, wouldn't it be better to name them both `bvnego` and `bvdivo`, OR better yet `bvsnego` and `bvsdivo`? My vote would be for the latter pair.

Clark Barrett answered:

Here's the rationale for the current naming scheme.

If there's an existing bv operator that can overflow in exactly one way, we just add "o" to the name of the operator.  This is the case for bvneg and bvsdiv.  If an operator can overflow in more than one way, then we add "u" or "s" to disambiguate it, which is why we have bvuaddo and bvsaddo, etc.

I do see your point, but on the other hand, we don't have a bvsneg operator, and bvneg can only overflow in one way, so in that sense, I think it's better to just stick with bvnego.

**Comment by LeventErkok** [comment]
Hi Pascal (@fontainep):

Thanks for pushing this through. I should say that I find the current naming confusing as an end-user, but I see from this thread that it was discussed in depth so I won't add to that fire, except for a little comment below.

However, I wanted to point out two things in the proposed changes, which seem problematic to me.

`bvnego` predicate
--
You define:  `[[(bvnego s)]] := bv2int([[s]]) >= 2^(m - 1)`

This doesn't seem quite right to me. Let `m = 3`, and `s = #b100`. In this case the negation overflows. But `bv2int` will produce `-4`, which is definitely not `>= 4`.

I can think of two ways to fix it. You can either define:

`[[(bvnego s)]] := bv2nat([[s]]) >= 2^(m - 1)`

(i.e., use `bv2nat` instead of `bv2int`).

Alternatively, you can also define:

`[[(bvnego s)]] := bv2int([[s]]) == -(2^(m - 1))`

I like this second version better, since it makes the signed-ness nature of the operation clear. (I should add that this is why I think the name `bvnego` is very confusing: We should go for `bvsnego` to signal to the end-user that the argument will be treated as a signed-2's complement value. In fact, I'd even be OK adding `bvunego` which always returns `false`. That is, the name should follow how the argument will be treated, not whether it can overflow or not. But let's not digress on the names here. As Clark mentioned I can see both arguments for how the naming should go as well.)

`bvsaddo` definition
--
You say: `(bvssubo s t) abbreviates (or (bvsaddo s (bvneg t)) (and (bvnego t) (bvslt s (_ bv0 m))))`

This seems wrong to me. Again, let `m = 3`, `s = #b111`, and `t = #b100`. That is, `s = -1` and `t = -4`. Subtraction gives `-1 - (-4) = 3`, which does NOT overflow.

On the right handside, however, we have: `bvneg t`, which produces `-4` since it overflows. Then we ask if signed-addition of `-1` and `-4` overflow, which is `-5` and it indeed does overflow. The disjunction becomes true, so the right-hand-side indicates the overall operation DOES overflow.

These two results seem to mismatch. Am I interpreting your definition incorrectly?

**Comment by fontainep** [comment]
Hi Levent,

thanks a lot for your quick and insightful answer.!  There are indeed quite a few mistakes.  Really sorry for that.

bvneg only overflows for the smallest integer, which is 2^(m-1) in unsigned or -2^(m-1) in signed

[[(bvnego s)]] := bv2nat([[s]]) == 2^(m - 1)

[[(bvnego s)]] := bv2int([[s]]) == -2^(m - 1)

Using >= is a further mistake of mine.

For bvssubo, the idea behind such a complicated expression is to relate to bvsaddo: bvssub overflows if the addition overflows when the negation does not, or if the negation overflows (t is the smallest signed integer) and t is substracted from a positive number.

(bvssubo s t) abbreviates (ite (bvnego t) (bvsge s (_ bv0 m)) (bvsaddo s (bvneg t)))

Am I right now?

**Comment by LeventErkok** [comment]
Hi Pascal: Yes, I think your fixes are good. (I still prefer the second version of the `bvnego` predicate, but as you mentioned they are equivalent.)

**Comment by fontainep** [comment]
Hi Levent,
thanks again for your careful read and comments.
Here are two new files.
[FixedSizeBitVectors.smt2.txt](https://github.com/SMT-LIB/SMT-LIB-2/files/13504043/FixedSizeBitVectors.smt2.txt)
[QF_BV.smt2.txt](https://github.com/SMT-LIB/SMT-LIB-2/files/13504044/QF_BV.smt2.txt)

**Comment by barrettcw** [comment]
Fixed in 2.7
